# This is a basic workflow to help you get started with Actions

name: Deliver as Docker Image

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main, devops-cd ]
  workflow_dispatch:

jobs:
  build-container:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo 
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Build Docker Container
        run: docker build -t o2buzzle/oner-backend .
      - name: Docker Login
        uses: docker/login-action@v2.0.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Push to Docker Hub
        run: docker push o2buzzle/oner-backend
